name: sisfarma
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter: 
    sdk: flutter 
  cupertino_icons: ^1.0.6
  # Splash Screen
  flutter_native_splash: ^2.4.0
  # State Management
  get_cli: ^1.8.1
  get: ^4.6.6
#  app icon
  flutter_launcher_icons: ^0.13.1
#  barcode scanner
  flutter_barcode_scanner: ^2.0.0

  

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true


  assets:
    - assets/icon/

flutter_icons:
#   android: "launcher_icon"
   android: true
   ios: true
   image_path: "assets/icon/app_icon.png"


  # Splash Screen
flutter_native_splash:
  color: "#ffffff"
  image: "assets/icon/app_icon.png"
  # branding: assets/branding-development.png
  color_dark: "#121212"
  image_dark: "assets/icon/app_icon.png"
     # branding_dark: assets/branding-development.png

  android_12:
   image: "assets/icon/app_icon.png"
   icon_background_color: "#ffffff"
   image_dark: "assets/icon/app_icon.png"
   icon_background_color_dark: "#121212"






